version: '3'
services:
  looping:
    image: ubuntu:latest
    container_name: looping
    hostname: looping
    build:
      context: ./
      dockerfile: looping-Dockerfile
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
      - ./script.sh:/usr/local/script.sh
      - /opt/logs:/opt/logs:rw
    entrypoint: bash /usr/local/script.sh

